
version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: ecommerce_postgres
    restart: always
    environment:
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_net

  mongodb:
    image: mongo:6
    container_name: ecommerce_mongo
    restart: always
    ports:
      - "27017:27018"
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: ecommerce_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - ecommerce_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: ecommerce_kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - ecommerce_net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: ecommerce_logstash
    ports:
      - "5050:5000"  # For TCP logging
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    networks:
      - ecommerce_net

volumes:
  postgres_data:
  mongo_data:
  es_data:

networks:
  ecommerce_net:
    driver: bridge
